const flow=['Обнаружение','Взаимный интерес','Разговор','Планирование','Встреча','Результат'];
const features=[['◉','Люди рядом','Геосценарии помогают увидеть актуальные возможности для знакомства.'],['↗','Путь к встрече','Продукт поддерживает движение от интереса к конкретному плану.'],['◇','Взаимное согласие','Ключевые действия строятся только на встречном интересе.'],['⌁','Safety UX','Публичные механики помогают сохранить контроль и прозрачность.'],['✦','После встречи','Сценарий не заканчивается в момент назначения встречи.'],['▦','Аналитика продукта','События помогают улучшать путь пользователя без раскрытия личных данных.']];
export default function Neryo(){return <main className="neryoCase"><nav className="caseNav"><a href="/" className="identity"><b>M</b><span>Max Volkov<small>Веб- и продуктовый разработчик</small></span></a><a href="/">← Все проекты</a></nav><header className="caseHero"><div><p className="chip">РЕАЛЬНЫЙ ПРОДУКТ · ACTIVE DEVELOPMENT</p><h1>NERYO</h1><h2>Знакомство должно вести <em>к чему-то настоящему.</em></h2><p>Мобильный продукт знакомств, построенный вокруг реальных встреч вместо бесконечной переписки.</p><span>Mobile · Social · Product</span></div><div className="casePhones"><article><small>12:42</small><b>N</b><strong>Люди,<br/>не анкеты.</strong><i>DISCOVERY</i></article><article><small>18:10</small><b>◉</b><strong>Спланируйте<br/>что-то настоящее.</strong><i>MEETING</i></article><div className="caseGlow"></div></div></header>
<section className="caseMeta"><p>Кейс показывает продукт на уровне портфолио. Исходный код, приватные API, production-конфигурация и закрытая бизнес-логика не публикуются.</p><div><b>РОЛЬ</b><span>Продукт · UX · Разработка</span><b>ПЛАТФОРМА</b><span>Мобильное приложение</span><b>СТАТУС</b><span>В активной разработке</span></div></section>
<section className="caseProblem"><p className="kicker">01 / ПРОБЛЕМА</p><h2>Бесконечный свайп<br/>не равен встрече.</h2><p>Дейтинг-продукты легко застревают в коллекционировании мэтчей и длинных переписках. NERYO исследует более прямой и взаимно согласованный путь к реальному общению.</p></section>
<section className="caseConcept"><div><p className="kicker">02 / КОНЦЕПЦИЯ</p><h2>Сценарий с понятным направлением</h2><p>Каждый этап снижает неопределённость и помогает участникам перейти к следующему шагу без давления.</p></div><div className="flow">{flow.map((x,i)=><article key={x}><b>0{i+1}</b><span>{x}</span>{i<flow.length-1&&<i>→</i>}</article>)}</div></section>
<section className="caseUx"><div><p className="kicker">03 / UX</p><h2>Сначала — реальный контекст.</h2><p>Discovery, взаимный интерес, разговор, планирование и аккуратный post-meeting experience собраны в один продуктовый путь.</p></div><div className="screenRow"><article><small>ЭКРАН 01</small><b>DISCOVERY</b><span>Место для безопасного реального скриншота</span></article><article><small>ЭКРАН 02</small><b>ПЛАН ВСТРЕЧИ</b><span>Место для безопасного реального скриншота</span></article><article><small>ЭКРАН 03</small><b>SAFETY / ИТОГ</b><span>Место для безопасного реального скриншота</span></article></div></section>
<section className="caseFeatures"><p className="kicker">04 / ВОЗМОЖНОСТИ</p><h2>Продуктовая глубина,<br/>а не набор экранов.</h2><div>{features.map(x=><article key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="caseComplex"><p className="kicker">05 / СЛОЖНОСТЬ ПРОДУКТА</p><h2>Production-oriented основа</h2><div>{['Мобильное приложение','Backend-сервисы','Геопространственная логика','Уведомления','Сценарии встреч','Safety-механики','Продуктовая аналитика','Масштабируемая архитектура'].map(x=><span key={x}>{x}</span>)}</div><small>Только высокоуровневое описание. Чувствительная архитектура и закрытая реализация не раскрываются.</small></section>
<section className="caseStatus"><div><p>СТАТУС</p><h2>Продукт в активной разработке</h2><span>Real product · Active development</span></div><a href="/">Вернуться к портфолио →</a></section><footer><p>© 2026 Max Volkov</p><p>NERYO — реальный приватный продукт. Исходный код не включён.</p></footer></main>}
