'use client';
import {useMemo,useState} from 'react';
import {contact} from '@/src/config/contact';
import {projectLinks} from '@/src/config/projects';

const projects=[
{tag:'РЕСТОРАН',name:'SERA',text:'Редакционный лендинг с интерактивным меню и быстрым бронированием.',href:projectLinks.restaurant,cls:'sera',image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=85'},
{tag:'ДЕТЕЙЛИНГ',name:'KERN',text:'Коммерческий сайт с услугами, пакетами и наглядным сравнением результата.',href:projectLinks.detailing,cls:'kern',image:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=85'},
{tag:'АРЕНДА НЕДВИЖИМОСТИ',name:'CASA AVELA',text:'Премиальная презентация виллы с галереей и расчётом проживания.',href:projectLinks.villa,cls:'casa',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85'}];
const plans=[
{icon:'↗',name:'Landing START',price:'от 24 900 ₽',text:'Быстрый запуск услуги или небольшой компании.',items:['Структура и до 6 блоков','Адаптивная вёрстка','Форма и базовая SEO','Публикация · 2 раунда правок']},
{icon:'◇',name:'BUSINESS',price:'от 39 900 ₽',text:'Расширенная подача для растущего бизнеса.',items:['Индивидуальная структура','7–10+ смысловых блоков','Интерактив и аналитика','Публикация · 2 раунда правок']},
{icon:'⬡',name:'INTERACTIVE',price:'от 59 900 ₽',text:'Когда нужен не просто лендинг.',items:['Квизы и калькуляторы','Каталоги и конфигураторы','API-интеграции','Нестандартная frontend-логика']},
{icon:'∞',name:'CUSTOM PRODUCT',price:'Индивидуально',text:'Цифровой продукт под задачу и процесс.',items:['MVP и web app','Внутренние сервисы','Мобильные продукты','Сложная продуктовая логика']}];
const process=[['01','Задача','Определяем цель и критерии результата.'],['02','Структура','Собираем сценарий без лишних блоков.'],['03','Концепция','Фиксируем визуальный язык проекта.'],['04','Разработка','Верстаю, оживляю и настраиваю.'],['05','Проверка','Тестирую экраны и сценарии.'],['06','Публикация','Запускаем и подключаем аналитику.']];
const capabilities=[['▦','Калькуляторы','Расчёт стоимости в реальном времени'],['◈','Квизы','Интерактивный подбор вариантов'],['▤','Мини-каталоги','Удобная навигация по товарам'],['▣','Витрины продуктов','Наглядная интерактивная подача'],['✦','AI-контент','Графика и рекламные материалы']];

export default function Home(){const[menu,setMenu]=useState(false);const[type,setType]=useState('Лендинг');const[sections,setSections]=useState(6);const[interactive,setInteractive]=useState(true);const[motion,setMotion]=useState(true);const estimate=useMemo(()=>24900+Math.max(0,sections-6)*1800+(type==='Интерактивный сайт'?18000:type==='MVP / сервис'?40000:0)+(interactive?9000:0)+(motion?6000:0),[type,sections,interactive,motion]);return <main className="portfolio">
<nav className="topbar"><a className="identity" href="#top"><b>M</b><span>Max Volkov<small>Веб- и продуктовый разработчик</small></span></a><div className={menu?'navlinks open':'navlinks'}>{['Работы','Услуги','Процесс','Возможности','Контакты'].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}</a>)}</div><a className="navcta" href="#контакты">Обсудить проект <span>→</span></a><button className="menubtn" onClick={()=>setMenu(v=>!v)} aria-label="Открыть меню">{menu?'×':'☰'}</button></nav>
<header id="top" className="hero"><div className="heroCopy"><p className="chip">Веб-разработка · Цифровые продукты</p><h1>Создаю современные <em>сайты</em> и <i>цифровые продукты</i> для бизнеса</h1><p className="lead">Лендинги, интерактивные сайты и цифровые продукты с фокусом на визуал, удобство и бизнес-задачу.</p><div className="actions"><a className="primary" href="#работы">Посмотреть работы <span>→</span></a><a className="secondary" href="#контакты">Обсудить проект</a></div><div className="heroStats"><span><b>4</b>проекта в портфолио</span><span><b>100%</b>адаптивный интерфейс</span><span><b>01</b>реальный продукт</span></div></div>
<div className="heroVisual" aria-label="Композиция интерфейсов"><div className="glow"></div><div className="browserCard"><div className="browserTop"><i></i><i></i><i></i><small>casa-avela.vercel.app</small></div><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1100&q=90" alt="Современная вилла у моря"/><div className="browserText"><small>CASA AVELA</small><strong>Архитектура<br/>для тишины</strong></div></div><div className="phoneCard"><span>12:48</span><b>N</b><strong>Встречи,<br/>а не свайпы.</strong><small>NERYO · PRODUCT</small></div><div className="metric"><small>Интерактив</small><b>+ глубина</b><i></i></div><div className="codeCard"><small>DESIGN / DEV</small><code>visual<br/>.build<br/>.launch</code></div><div className="orbit one"></div><div className="orbit two"></div></div></header>
<section id="работы" className="section projects"><div className="sectionHead"><div><p className="kicker">РЕАЛЬНЫЕ РЕШЕНИЯ</p><h2>Избранные проекты</h2></div><p>Каждый проект решает конкретную задачу. Эстетика, логика и результат работают вместе.</p></div><div className="projectGrid">{projects.map(p=><a key={p.name} className={`projectCard ${p.cls}`} href={p.href} target="_blank" rel="noreferrer"><img src={p.image} alt=""/><div className="projectShade"></div><span>{p.tag}</span><div><h3>{p.name}</h3><p>{p.text}</p><b>Открыть проект →</b></div></a>)}<a className="projectCard neryoCard" href="/neryo"><div className="neryoArt"><i></i><i></i><i></i><b>N</b></div><span>ФЛАГМАНСКИЙ ПРОДУКТ</span><div><h3>NERYO</h3><p>Мобильный продукт знакомств, который помогает перейти от интереса к реальной встрече.</p><ul><li>Продуктовый UX</li><li>Геосценарии</li><li>Safety-механики</li></ul><b>Смотреть кейс →</b></div></a></div></section>
<section id="услуги" className="section pricing"><div className="sectionHead"><div><p className="kicker">УСЛУГИ И ТАРИФЫ</p><h2>Выберите подходящий формат</h2></div><p>Гибкие решения под задачу — от лендинга до сложной веб-платформы.</p></div><div className="planGrid">{plans.map((p,i)=><article className={i===2?'plan featured':'plan'} key={p.name}><div className="planIcon">{p.icon}</div><h3>{p.name}</h3><p>{p.text}</p><strong>{p.price}</strong><ul>{p.items.map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul><a href="#контакты">{i===3?'Обсудить проект':'Заказать'} <span>→</span></a></article>)}</div></section>
<section id="процесс" className="section process"><div className="sectionHead"><div><p className="kicker">ПРОЦЕСС РАБОТЫ</p><h2>Как создаётся ваш проект</h2></div><p>Прозрачный процесс, понятные этапы и регулярная коммуникация.</p></div><div className="processLine">{process.map((x,i)=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p>{i<process.length-1&&<i>→</i>}</article>)}</div></section>
<section id="возможности" className="section capabilities"><div className="capCopy"><p className="kicker">БОЛЬШЕ ВОЗМОЖНОСТЕЙ</p><h2>Интерактивные решения для большего вовлечения</h2><p>Добавьте механику, которая помогает посетителю быстрее принять решение.</p><div className="capList">{capabilities.map(x=><article key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></article>)}</div></div><form className="calculator" onSubmit={e=>e.preventDefault()}><div className="calcTop"><span>Демонстрационный расчёт</span><b>◆</b></div><label>Тип проекта<select value={type} onChange={e=>setType(e.target.value)}><option>Лендинг</option><option>Интерактивный сайт</option><option>MVP / сервис</option></select></label><label>Количество секций <b>{sections}</b><input type="range" min="4" max="14" value={sections} onChange={e=>setSections(+e.target.value)}/></label><label className="toggle">Интерактивные элементы<input type="checkbox" checked={interactive} onChange={e=>setInteractive(e.target.checked)}/><i></i></label><label className="toggle">Продвинутые анимации<input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/><i></i></label><div className="calcTotal"><span>Ориентировочно</span><b>от {estimate.toLocaleString('ru-RU')} ₽</b><small>Финальная стоимость определяется после обсуждения задачи.</small></div><a href="#контакты">Обсудить расчёт →</a></form></section>
<section className="faq section"><div><p className="kicker">ВОПРОСЫ</p><h2>Перед стартом</h2></div><div>{[['Что нужно от клиента?','Задача, материалы о продукте и человек, который принимает решения. Остальное определим вместе.'],['Можно без готового дизайна?','Да. Структура и визуальная концепция входят в работу.'],['Можно изменить существующий сайт?','Да — от точечных улучшений до полноценного редизайна после оценки основы.'],['Что с доменом и хостингом?','Помогу выбрать, подключить и опубликовать. Сервисы оплачиваются отдельно.'],['Сколько занимает разработка?','Зависит от объёма и скорости согласований. Реалистичный график фиксируем после брифа.']].map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section id="контакты" className="contact"><div><p className="kicker">НАЧНЁМ ПРОЕКТ</p><h2>Готовы создать<br/><em>что-то особенное?</em></h2><p>Обсудим задачу и выберем подходящий формат реализации.</p></div><div className="contactActions"><a className="telegram" href={contact.telegram}>✦ Написать в Telegram</a><a href={`mailto:${contact.email}`}>✉ Написать на Email</a></div></section>
<footer><a className="identity" href="#top"><b>M</b><span>Max Volkov<small>Веб- и продуктовый разработчик</small></span></a><div><a href={contact.github}>GitHub</a><a href={contact.telegram}>Telegram</a><a href={`mailto:${contact.email}`}>Email</a><a href={contact.avito}>Avito</a></div><p>Designed & developed by Max Volkov · 2026</p></footer></main>}
