'use client';import{useState}from'react';import{contact}from'@/src/config/contact';import{projectLinks}from'@/src/config/projects';
const works=[{n:'01',title:'SERA',kind:'Landing / Restaurant',desc:'Меню, мобильный UX и бронирование в спокойной редакционной подаче.',href:projectLinks.restaurant||'#contact',class:'sera'},{n:'02',title:'KERN',kind:'Commercial Landing / Automotive',desc:'Услуги, before/after, пакеты и форма заявки с коммерческой логикой.',href:projectLinks.detailing||'#contact',class:'kern'},{n:'03',title:'CASA AVELA',kind:'Landing / Real Estate & Hospitality',desc:'Галерея, booking UI, калькулятор и премиальная презентация объекта.',href:projectLinks.villa||'#contact',class:'casa'}];
const plans=[['Landing START','от 24 900 ₽',['Структура и до 6 блоков','Адаптив и базовые анимации','Форма и базовая SEO-настройка','Публикация · 2 раунда правок']],['BUSINESS','от 39 900 ₽',['Индивидуальная структура · 7–10+ блоков','Сложный дизайн и интерактив','Формы и аналитика','Публикация · 2 раунда правок']],['INTERACTIVE','от 59 900 ₽',['Квизы и калькуляторы','Каталоги и конфигураторы','API-интеграции','Нестандартная frontend-логика']],['CUSTOM PRODUCT','Индивидуально',['MVP и web app','Внутренний сервис','Мобильный продукт','Сложная продуктовая логика']]] as const;
export default function Home(){const[menu,setMenu]=useState(false);return <main><nav><a href="#top" className="logo">MV.</a><div className={menu?'open':''}><a href="#work">Работы</a><a href="#services">Услуги</a><a href="#process">Процесс</a><a href="#contact">Контакт</a></div><button onClick={()=>setMenu(!menu)} aria-label="Меню">{menu?'×':'☰'}</button></nav>
<header id="top"><p className="over">WEB DEVELOPER · 2026</p><h1>Сайты, которые<br/>помогают <i>делу.</i></h1><div className="heroFoot"><p>Создаю современные сайты и цифровые продукты для бизнеса: от небольшого лендинга до интерактивного сервиса и MVP.</p><div><a className="primary" href="#work">Посмотреть работы ↓</a><a href="#contact">Обсудить проект ↗</a></div></div><span className="orb">M<br/>V</span></header>
<section className="marquee"><span>DESIGN × DEVELOPMENT × INTERACTION × PRODUCT THINKING × </span></section>
<section id="work" className="work"><div className="heading"><p>01 / ИЗБРАННЫЕ РАБОТЫ</p><h2>Не один шаблон.<br/>Разные задачи — разные решения.</h2></div>{works.map(w=><a className={`workCard ${w.class}`} href={w.href} key={w.n}><span>{w.n}</span><div><small>{w.kind}</small><h3>{w.title}</h3><p>{w.desc}</p></div><b>↗</b></a>)}</section>
<section className="neryo"><div className="neryoCopy"><p>04 / FLAGSHIP PRODUCT · REAL PRODUCT</p><h2>NERYO</h2><h3>От знакомства —<br/>к реальной встрече.</h3><p>Мобильный продукт знакомств, построенный вокруг реальных встреч вместо бесконечной переписки.</p><a href="/neryo">Открыть case study ↗</a></div><div className="phones"><div><span>12:42</span><b>N</b><h4>People, not profiles.</h4><i>DISCOVER</i></div><div><span>18:10</span><b>◉</b><h4>Plan something real.</h4><i>MEETING</i></div><small>REPRESENTATIVE PLACEHOLDERS<br/>REAL SCREENSHOTS TO BE ADDED</small></div></section>
<section id="services" className="services"><div className="heading"><p>02 / УСЛУГИ</p><h2>Понятный объём.<br/>Честная отправная цена.</h2></div><div className="plans">{plans.map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><b>{p[1]}</b><ul>{p[2].map(x=><li key={x}>{x}</li>)}</ul><a href="#contact">Обсудить ↗</a></article>)}</div><div className="extras"><h3>Дополнительно</h3><p>Редизайн существующего сайта · мобильная адаптация · доведение AI-generated сайтов · калькуляторы · квизы · каталоги · формы · аналитика · небольшие интеграции.</p></div></section>
<section id="process" className="process"><div className="heading"><p>03 / КАК РАБОТАЕМ</p><h2>От задачи<br/>до запуска.</h2></div><div>{[['01','Задача','Разбираемся, что сайт должен изменить для бизнеса.'],['02','Структура','Собираем сценарий и приоритеты без лишних блоков.'],['03','Концепция','Фиксируем визуальное направление и тон.'],['04','Разработка','Верстаю, оживляю и настраиваю адаптив.'],['05','Проверка','Проверяю экраны, состояния и основные сценарии.'],['06','Правки','Два согласованных раунда в рамках задачи.'],['07','Публикация','Подключаем домен, аналитику и запускаем.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="faq"><div className="heading"><p>04 / FAQ</p><h2>Перед стартом.</h2></div>{[['Что нужно от клиента?','Понимание задачи, материалы о продукте и один человек, который принимает решения. Если чего-то нет — определим вместе.'],['Можно без готового дизайна?','Да. Структура и визуальная концепция входят в работу.'],['Можно изменить существующий сайт?','Да — от точечных улучшений до полноценного редизайна. Сначала оценю текущую основу.'],['Что с доменом и хостингом?','Помогу выбрать, подключить и опубликовать. Сервисы оплачиваются владельцем проекта отдельно.'],['Можно редактировать после запуска?','Да. Способ зависит от типа сайта: код, CMS или отдельная договорённость на поддержку.'],['Что считается правкой?','Изменение согласованного решения, не меняющее исходную задачу или весь сценарий страницы.'],['Сколько занимает разработка?','Зависит от объёма и скорости согласований. Реалистичный график определяем после короткого брифа.']].map(x=><details key={x[0]}><summary>{x[0]}<b>+</b></summary><p>{x[1]}</p></details>)}</section>
<section id="contact" className="contact"><p>ЕСТЬ ЗАДАЧА?</p><h2>Давайте сделаем<br/><i>хороший сайт.</i></h2><div>{contact.telegram?<a href={contact.telegram}>Telegram ↗</a>:<span>Telegram · добавить в config</span>}{contact.email?<a href={`mailto:${contact.email}`}>{contact.email}</a>:<span>Email · добавить в config</span>}</div><small>Контакты намеренно не выдуманы. Заполните src/config/contact.ts перед публикацией.</small></section>
<footer><a className="logo" href="#top">MV.</a><p>© 2026 Max Volkov</p><p>Designed & developed by Max Volkov</p><a href="#top">Наверх ↑</a></footer></main>}
